# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7934b3d90354743f4de7c6dfae5de486c295afbace57b57d9d31b67bccf911b0763a21e548343686941a6350d3894e72f9c00bf91f3cb81ae7cccc1be7f2c124

test:
  secret_key_base: 3c9f128f38d6f1604b50c170c98c37c4e96e5caeeb8136d5059fd912884d04c2791996b656e4ed09a543a3eb3074a535c4e4688f27f9030bd9b8bbd70f479c07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
